use crate::wasd::Stats;

use prometheus_exporter_base::prelude::*;

macro_rules! metrics_for {
    ($metrics:ident, $channels:expr, $($metric:ident $(as $type:ident)?),* ) => {
        $(
            let mut metric: PrometheusMetric = PrometheusMetric::build()
            .with_metric_type(MetricType::Gauge)
            .with_name(stringify!($metric))
            .with_help("Autogenerated")
            .build();
            for stats in &$channels {
                let instance = PrometheusInstance::new()
                    .with_label("channel", &*stats.channel_name)
                    .with_value(stats.$metric $(as $type)?);
                metric.render_and_append_instance(&instance);
            }
            $metrics.push(metric);
          )*
    };
}

pub(crate) fn generate_metrics(stats: Vec<Stats>) -> String {
    let mut metrics = vec![];
    metrics_for!(
        metrics,
        stats,
        channel_clips_count,
        channel_id,
        channel_is_live as u8,
        channel_priority,
        followers_count,
        is_partner as u8,
        stream_total_viewers,
        stream_current_viewers,
        stream_current_active_viewers
    );
    metrics
        .into_iter()
        .map(|x| x.render())
        .collect::<Vec<_>>()
        .join("")
}

#[cfg(test)]
mod tests {

    use crate::wasd::Stats;

    use super::generate_metrics;

    #[test]
    fn test_metrics() {
        let stats = vec![
            Stats {
                channel_clips_count: 0,
                channel_id: 123,
                channel_is_live: true,
                channel_priority: 0.0,
                followers_count: 100,
                is_partner: false,
                channel_name: "aboba".into(),
                stream_total_viewers: 16,
                stream_current_viewers: 3,
                stream_current_active_viewers: 3,
            },
            Stats {
                channel_clips_count: 0,
                channel_id: 123,
                channel_is_live: false,
                channel_priority: 0.0,
                followers_count: 100,
                is_partner: false,
                channel_name: "abiba".into(),
                stream_total_viewers: 0,
                stream_current_viewers: 0,
                stream_current_active_viewers: 0,
            },
        ];
        let metrics = generate_metrics(stats);
        println!("{metrics}");
        let res = r#"
# HELP channel_clips_count Autogenerated
# TYPE channel_clips_count gauge
channel_clips_count{channel="aboba"} 0
channel_clips_count{channel="abiba"} 0
# HELP channel_id Autogenerated
# TYPE channel_id gauge
channel_id{channel="aboba"} 123
channel_id{channel="abiba"} 123
# HELP channel_is_live Autogenerated
# TYPE channel_is_live gauge
channel_is_live{channel="aboba"} 1
channel_is_live{channel="abiba"} 0
# HELP channel_priority Autogenerated
# TYPE channel_priority gauge
channel_priority{channel="aboba"} 0
channel_priority{channel="abiba"} 0
# HELP followers_count Autogenerated
# TYPE followers_count gauge
followers_count{channel="aboba"} 100
followers_count{channel="abiba"} 100
# HELP is_partner Autogenerated
# TYPE is_partner gauge
is_partner{channel="aboba"} 0
is_partner{channel="abiba"} 0
# HELP stream_total_viewers Autogenerated
# TYPE stream_total_viewers gauge
stream_total_viewers{channel="aboba"} 16
stream_total_viewers{channel="abiba"} 0
# HELP stream_current_viewers Autogenerated
# TYPE stream_current_viewers gauge
stream_current_viewers{channel="aboba"} 3
stream_current_viewers{channel="abiba"} 0
# HELP stream_current_active_viewers Autogenerated
# TYPE stream_current_active_viewers gauge
stream_current_active_viewers{channel="aboba"} 3
stream_current_active_viewers{channel="abiba"} 0
"#;
        assert_eq!(metrics.trim(), res.trim())
    }
}
